"""create ticket events table

Revision ID: 539c99659f46
Revises: ba0161dd4076
Create Date: 2026-09-25 19:19:53.675504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539c99659f46'
down_revision: Union[str, Sequence[str], None] = 'ba0161dd4076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enum CHECK declared explicitly (create_constraint=False) to avoid a duplicate.
    op.create_table('ticket_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'ASSIGNED', 'STATUS_CHANGED', 'PRIORITY_CHANGED', 'CATEGORY_CHANGED', 'RESOLVED', 'CLOSED', 'REOPENED', name='ticket_action', native_enum=False, create_constraint=False, length=26), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('CREATED', 'ASSIGNED', 'STATUS_CHANGED', 'PRIORITY_CHANGED', 'CATEGORY_CHANGED', 'RESOLVED', 'CLOSED', 'REOPENED')", name=op.f('ck_ticket_events_ticket_action')),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_ticket_events_changed_by_id_users')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_events_ticket_id_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_events'))
    )
    op.create_index('ix_ticket_events_ticket_id_created_at', 'ticket_events', ['ticket_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_events_ticket_id_created_at', table_name='ticket_events')
    op.drop_table('ticket_events')
    # ### end Alembic commands ###
