"""create ticket comments table

Revision ID: 2355a1a6f2c5
Revises: 539c99659f46
Create Date: 2026-09-25 19:29:50.963185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2355a1a6f2c5'
down_revision: Union[str, Sequence[str], None] = '539c99659f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_ticket_comments_author_id_users')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_comments_ticket_id_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_comments'))
    )
    op.create_index('ix_ticket_comments_ticket_id_created_at', 'ticket_comments', ['ticket_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_comments_ticket_id_created_at', table_name='ticket_comments')
    op.drop_table('ticket_comments')
    # ### end Alembic commands ###
