"""make category names unique ignoring case

Revision ID: ba0161dd4076
Revises: d1acf384ba6f
Create Date: 2026-09-25 19:08:21.918164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0161dd4076'
down_revision: Union[str, Sequence[str], None] = 'd1acf384ba6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Case-insensitive uniqueness enforced by the database, not only by the service.
    op.drop_constraint(op.f('uq_categories_name'), 'categories', type_='unique')
    op.create_index('uq_categories_name_lower', 'categories', [sa.text("lower(name)")], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_categories_name_lower', table_name='categories')
    op.create_unique_constraint(op.f('uq_categories_name'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
